import "./globals.css";
import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import { Providers } from "./providers";
import { LifiWidgetDrawerProvider } from "./dynamic";
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <meta
          name="viewport"
          content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no"
        />
      </head>
      <body
        className={`min-h-screen min-w-full bg-background ${geistSans.variable} ${geistMono.variable} antialiased touch-manipulation`}
      >
        <Providers>
          <LifiWidgetDrawerProvider>{children}</LifiWidgetDrawerProvider>
        </Providers>
      </body>
    </html>
  );
}
